export function getInitScript() {
  /* eslint-disable no-template-curly-in-string */
  const lines = [
    'export CLOAK_SHELL_INTEGRATION=1',
    '',
    'cloak() {',
    '  if [ "$1" = "switch" ] || [ "$1" = "use" ]; then',
    '    shift',
    '    local output',
    '    output=$(command cloak switch --print-env "$@")',
    '    local exit_code=$?',
    '    if [ $exit_code -eq 0 ]; then',
    '      eval "$output"',
    '    fi',
    '  else',
    '    command cloak "$@"',
    '  fi',
    '}',
    '',
    'claude() {',
    '  if [ "$1" = "account" ]; then',
    '    local subcmd="$2"',
    '    shift 2',
    '    if [ "$subcmd" = "switch" ] || [ "$subcmd" = "use" ]; then',
    '      local output',
    '      output=$(command cloak switch --print-env "$@")',
    '      local exit_code=$?',
    '      if [ $exit_code -eq 0 ]; then',
    '        eval "$output"',
    '      fi',
    '    else',
    '      command cloak "$subcmd" "$@"',
    '    fi',
    '  elif [ "$1" = "-a" ] && [ -n "$2" ]; then',
    '    local name="$2"',
    '    shift 2',
    '    local output',
    '    output=$(command cloak switch --print-env "$name")',
    '    local exit_code=$?',
    '    if [ $exit_code -eq 0 ]; then',
    '      eval "$output"',
    '      command cloak context-bar claude',
    '      command claude "$@"',
    '    fi',
    '  else',
    '    if [ -f ".cloak" ]; then',
    '      local _bind_name',
    '      _bind_name=$(cat .cloak 2>/dev/null | tr -d "[:space:]")',
    '      if [ -n "$_bind_name" ]; then',
    '        local _bind_output',
    '        _bind_output=$(command cloak switch --print-env "$_bind_name" 2>/dev/null)',
    '        if [ $? -eq 0 ]; then',
    '          eval "$_bind_output"',
    '        fi',
    '      fi',
    '    fi',
    '    if [ -n "$CLAUDE_CONFIG_DIR" ]; then',
    '      command cloak context-bar claude',
    '    fi',
    '    command claude "$@"',
    '  fi',
    '}',
  ]
  return lines.join('\n') + '\n'
}

export async function initShell() {
  process.stdout.write(getInitScript())
}
